name = "cf-worker-shorturl"
main = "src/index.js"
compatibility_date = "2023-04-13"
node_compat = true

[[kv_namespaces]]
binding = "LINKS"
id = "bae2fb854453426ba463b1dc32404f50" ## Change it to yours
[build]
command = "npm run build"
[vars]
USERNAME = "hoching" # Change it and don't expose it in this file
PASSWORD = "Ll2008727" # Change it and don't expose it in this file
JWT_SECRET = "Xx9f&`'?jQ!U+)*6B^2ZgK" # Change it and don't expose it in this file
DEFAULT_PAGE = "https://url-shorter.qwq.today/" # Change it
RECORD_CLICKS = false
FE_ADMIN_DOMAIN = "https://url-shorter.qwq.today/" #Remember to replace it with your admin domain, important for cross origin allowlist


